// Changelog data per version and locale
const CHANGELOG_DATA = {
  '2.5': {
    en: [
      'Major performance optimization: smoother dragging, faster speech recognition rendering, and reduced main-thread work during ChatGPT streaming.',
      'Theme selector: Light / Dark / System — dark mode is fully restyled and follows your OS live.',
      'Voice punctuation commands now work in your dictation language (~30 languages) — say "comma" or "запятая" and get "," with no stray space.',
      'Word replacements now work in any language and ignore case.',
      'Language picker with instant search and a scrollable list.',
      'Content width slider extended to 300% and made resilient to ChatGPT layout changes.',
      'Extension popup: Center Mic, Center Panel, and Open Settings buttons.',
      'Floating controls reliably keep their position — offscreen positions are recovered and clamped to the viewport.',
      'Removed the obsolete "Auto continue" option.',
    ],
    ru: [
      'Масштабная оптимизация производительности: более плавное перетаскивание, быстрая отрисовка распознавания речи, меньше нагрузки на главный поток при стриминге ChatGPT.',
      'Выбор темы: Светлая / Тёмная / Системная — тёмный режим полностью переработан и следует за ОС в реальном времени.',
      'Голосовые команды пунктуации теперь работают на языке диктовки (~30 языков) — скажите «запятая» или "comma" и получите «,» без лишнего пробела.',
      'Автозамена слов теперь работает на любом языке и не зависит от регистра.',
      'Выбор языка с мгновенным поиском и прокручиваемым списком.',
      'Слайдер ширины контента расширен до 300% и устойчив к изменениям вёрстки ChatGPT.',
      'Popup расширения: кнопки «Центрировать микрофон», «Центрировать панель» и «Открыть настройки».',
      'Плавающие элементы надёжно держат позицию — позиции за пределами экрана восстанавливаются и прижимаются к краям.',
      'Удалена устаревшая опция «Автопродолжение ответов».',
    ],
    es: [
      'Optimización importante de rendimiento: arrastre más suave, renderizado de reconocimiento de voz más rápido y menos trabajo en el hilo principal durante el streaming de ChatGPT.',
      'Selector de tema: Claro / Oscuro / Sistema — el modo oscuro está completamente rediseñado y sigue al SO en tiempo real.',
      'Los comandos de puntuación por voz ahora funcionan en tu idioma de dictado (~30 idiomas) — di "coma" o "comma" y obtén "," sin espacio extra.',
      'Los reemplazos de palabras ahora funcionan en cualquier idioma e ignoran mayúsculas.',
      'Selector de idioma con búsqueda instantánea y lista desplazable.',
      'Deslizador de ancho de contenido ampliado al 300% y resistente a los cambios de diseño de ChatGPT.',
      'Popup de la extensión: botones Centrar micrófono, Centrar panel y Abrir ajustes.',
      'Los controles flotantes mantienen su posición de forma fiable — las posiciones fuera de pantalla se recuperan y se ajustan al viewport.',
      'Eliminada la opción obsoleta "Continuar automáticamente".',
    ],
    fr: [
      'Optimisation majeure des performances : glisser plus fluide, rendu plus rapide de la reconnaissance vocale et moins de travail sur le thread principal pendant le streaming de ChatGPT.',
      'Sélecteur de thème : Clair / Sombre / Système — le mode sombre est entièrement restylé et suit l\'OS en temps réel.',
      'Les commandes vocales de ponctuation fonctionnent désormais dans votre langue de dictée (~30 langues) — dites « virgule » ou "comma" et obtenez « , » sans espace superflu.',
      'Les remplacements de mots fonctionnent désormais dans n\'importe quelle langue et ignorent la casse.',
      'Sélecteur de langue avec recherche instantanée et liste défilante.',
      'Curseur de largeur de contenu étendu à 300 % et résistant aux changements de mise en page de ChatGPT.',
      'Popup de l\'extension : boutons Centrer le micro, Centrer le panneau et Ouvrir les paramètres.',
      'Les contrôles flottants conservent leur position de façon fiable — les positions hors écran sont récupérées et limitées au viewport.',
      'Suppression de l\'option obsolète « Continuer automatiquement ».',
    ],
    hi: [
      'प्रमुख प्रदर्शन अनुकूलन: अधिक सहज ड्रैगिंग, तेज़ भाषण पहचान रेंडरिंग, और ChatGPT स्ट्रीमिंग के दौरान कम मेन-थ्रेड कार्य।',
      'थीम चयनकर्ता: लाइट / डार्क / सिस्टम — डार्क मोड पूरी तरह नया है और OS को रीयल-टाइम में फ़ॉलो करता है।',
      'वॉइस विराम चिह्न कमांड अब आपकी डिक्टेशन भाषा में काम करती हैं (~30 भाषाएँ) — "comma" या "अल्पविराम" बोलें और बिना अतिरिक्त स्पेस के "," पाएँ।',
      'शब्द प्रतिस्थापन अब किसी भी भाषा में काम करते हैं और अपरकेस/लोअरकेस को अनदेखा करते हैं।',
      'तुरंत खोज और स्क्रॉल करने योग्य सूची के साथ भाषा चयनकर्ता।',
      'कंटेंट चौड़ाई स्लाइडर 300% तक बढ़ाया गया और ChatGPT लेआउट बदलावों के प्रति मज़बूत बनाया गया।',
      'एक्सटेंशन पॉपअप: माइक्रोफ़ोन केंद्रित करें, पैनल केंद्रित करें और सेटिंग्स खोलें बटन।',
      'फ़्लोटिंग कंट्रोल अपनी स्थिति विश्वसनीय रूप से बनाए रखते हैं — स्क्रीन से बाहर की स्थितियाँ पुनर्प्राप्त होकर व्यूपोर्ट तक सीमित होती हैं।',
      'अप्रचलित "ऑटो कंटिन्यू" विकल्प हटा दिया गया।',
    ],
    ko: [
      '주요 성능 최적화: 더 부드러운 드래그, 더 빠른 음성 인식 렌더링, ChatGPT 스트리밍 중 메인 스레드 작업 감소.',
      '테마 선택기: 라이트 / 다크 / 시스템 — 다크 모드가 완전히 새로 디자인되고 OS를 실시간으로 따릅니다.',
      '음성 문장 부호 명령이 이제 받아쓰기 언어로 작동합니다(~30개 언어) — "쉼표" 또는 "comma"라고 말하면 불필요한 공백 없이 ","가 입력됩니다.',
      '단어 치환이 이제 모든 언어에서 작동하며 대소문자를 구분하지 않습니다.',
      '즉시 검색과 스크롤 목록이 있는 언어 선택기.',
      '콘텐츠 너비 슬라이더가 300%까지 확장되고 ChatGPT 레이아웃 변경에 강해졌습니다.',
      '확장 프로그램 팝업: 마이크 가운데 정렬, 패널 가운데 정렬, 설정 열기 버튼.',
      '플로팅 컨트롤이 위치를 안정적으로 유지 — 화면 밖 위치는 복구되어 뷰포트 안으로 제한됩니다.',
      '더 이상 사용되지 않는 "자동 계속" 옵션을 제거했습니다.',
    ],
    pt: [
      'Otimização importante de desempenho: arrasto mais suave, renderização mais rápida do reconhecimento de voz e menos trabalho na thread principal durante o streaming do ChatGPT.',
      'Seletor de tema: Claro / Escuro / Sistema — o modo escuro foi totalmente reformulado e segue o SO em tempo real.',
      'Comandos de pontuação por voz agora funcionam no seu idioma de ditado (~30 idiomas) — diga "vírgula" ou "comma" e obtenha "," sem espaço extra.',
      'Substituições de palavras agora funcionam em qualquer idioma e ignoram maiúsculas.',
      'Seletor de idioma com busca instantânea e lista rolável.',
      'Controle de largura de conteúdo estendido até 300% e resistente às mudanças de layout do ChatGPT.',
      'Popup da extensão: botões Centralizar microfone, Centralizar painel e Abrir configurações.',
      'Controles flutuantes mantêm a posição de forma confiável — posições fora da tela são recuperadas e limitadas ao viewport.',
      'Removida a opção obsoleta "Continuar automaticamente".',
    ],
    uk: [
      'Масштабна оптимізація продуктивності: плавніше перетягування, швидший рендерінг розпізнавання мови, менше навантаження на головний потік під час стрімінгу ChatGPT.',
      'Вибір теми: Світла / Темна / Системна — темний режим повністю перероблено та він слідкує за ОС у реальному часі.',
      'Голосові команди розділових знаків тепер працюють мовою диктування (~30 мов) — скажіть «кома» або "comma" й отримайте «,» без зайвого пробілу.',
      'Автозаміна слів тепер працює будь-якою мовою та не залежить від регістру.',
      'Вибір мови з миттєвим пошуком та списком із прокручуванням.',
      'Слайдер ширини контенту розширено до 300% і він стійкий до змін верстки ChatGPT.',
      'Popup розширення: кнопки «Центрувати мікрофон», «Центрувати панель» та «Відкрити налаштування».',
      'Плаваючі елементи надійно тримають позицію — позиції за межами екрана відновлюються та притискаються до країв.',
      'Видалено застарілу опцію «Автопродовження відповідей».',
    ],
    zh: [
      '重大性能优化：更流畅的拖拽、更快的语音识别渲染，以及减少 ChatGPT 流式传输期间的主线程工作。',
      '主题选择器：浅色 / 深色 / 系统 — 深色模式全面重新设计并实时跟随操作系统。',
      '语音标点命令现在支持您的听写语言（约30种语言）— 说"逗号"或"comma"即可得到","，不会有多余空格。',
      '单词替换现在支持任何语言且不区分大小写。',
      '语言选择器支持即时搜索和滚动列表。',
      '内容宽度滑块扩展至300%，并能适应 ChatGPT 布局变化。',
      '扩展弹出菜单：居中麦克风、居中面板和打开设置按钮。',
      '浮动控件可靠地保持位置 — 超出屏幕的位置会被恢复并限制在视口内。',
      '移除了过时的"自动继续"选项。',
    ],
  },
  '2.4': {
    en: [
      'Smoother interim speech recognition spacing — spaces appear as words are recognized instead of after finalization.',
      'Security and reliability hardening: tightened resource exposure and fixed message handler leaks.',
      'Settings modal visually refreshed: modern header, card layout, two-column language grid, and compact footer.',
    ],
    ru: [
      'Более плавное распознавание речи — пробелы между словами появляются сразу, а не после финализации.',
      'Улучшения безопасности и надёжности: ограничен доступ к ресурсам расширения, исправлены утечки обработчиков сообщений.',
      'Окно настроек обновлено внешне: современный заголовок, карточки, двухколоночная сетка языков и компактный подвал.',
    ],
    es: [
      'Espaciado más fluido de los resultados intermedios de reconocimiento de voz: los espacios aparecen a medida que se reconocen las palabras, en lugar de después de la finalización.',
      'Mayor seguridad y fiabilidad: reducida la exposición de recursos y corregidas fugas de manejadores de mensajes.',
      'Modal de ajustes renovado visualmente: encabezado moderno, diseño de tarjetas, cuadrícula de idiomas en dos columnas y pie compacto.',
    ],
    fr: [
      "Espacement plus fluide des résultats intermédiaires de reconnaissance vocale — les espaces apparaissent au fur et à mesure que les mots sont reconnus, au lieu d'apparaître après finalisation.",
      "Renforcement de la sécurité et de la fiabilité : exposition des ressources réduite et fuites de gestionnaires de messages corrigées.",
      "Modal des paramètres rafraîchi visuellement : en-tête moderne, disposition en cartes, grille de langues sur deux colonnes et pied de page compact.",
    ],
    hi: [
      'अंतरिम भाषण पहचान में अधिक सहज जगह — शब्द पहचानते ही स्पेस दिखाई देते हैं, अंतिम रूप देने के बाद नहीं।',
      'सुरक्षा और विश्वसनीयता में सुधार: संसाधन एक्सपोज़र कड़ा किया गया और संदेश हैंडलर लीक ठीक किए गए।',
      'सेटिंग्स मोडल को दिखने में नया रूप दिया गया: आधुनिक हेडर, कार्ड लेआउट, दो-कॉलम भाषा ग्रिड और कॉम्पैक्ट फुटर।',
    ],
    ko: [
      '더 부드러운 중간 음성 인식 간격 — 단어가 인식되는 즉시 공백이 표시되어 최종 변환 후에만 나타나지 않습니다.',
      '보안 및 안정성 강화: 리소스 노출을 줄이고 메시지 핸들러 누수를 수정했습니다.',
      '설정 모달 UI 개선: 현대적인 헤더, 카드 레이아웃, 2열 언어 그리드, 컴팩트한 푸터.',
    ],
    pt: [
      'Espaçamento mais suave dos resultados intermediários de reconhecimento de voz — os espaços aparecem à medida que as palavras são reconhecidas, em vez de só após a finalização.',
      'Endurecimento de segurança e confiabilidade: exposição de recursos reduzida e vazamentos de manipuladores de mensagens corrigidos.',
      'Modal de configurações renovado visualmente: cabeçalho moderno, layout em cartões, grade de idiomas em duas colunas e rodapé compacto.',
    ],
    uk: [
      'Більш плавне розпізнавання мови — пробіли між словами з’являються одразу, а не після фіналізації.',
      'Покращення безпеки та надійності: обмежено доступ до ресурсів розширення, виправлено витоки обробників повідомлень.',
      'Вікно налаштувань оновлено візуально: сучасний заголовок, картковий макет, двоколонкова сітка мов і компактний підвал.',
    ],
    zh: [
      '更流畅的临时语音识别间距 — 空格会在识别单词时立即出现，而不是等到最终确定后才显示。',
      '安全性与可靠性增强：收紧资源暴露范围，并修复消息处理程序泄漏。',
      '设置窗口视觉升级：现代标题、卡片布局、双列语言网格、紧凑页脚。',
    ],
  },
  '2.3': {
    en: [
      'Line break support during dictation — press Shift+Enter while the microphone is on.',
      'Tip: pause briefly before inserting a line break to let the current text finalize.',
      'Fixed duplicate text that occurred when rebase happened during recognition.',
      'Manual edits are now preserved while dictation is active.',
      'Settings modal redesign: close button (X), cleaner layout.',
    ],
    ru: [
      'Поддержка переноса строки во время диктовки — нажмите Shift+Enter, пока микрофон включён.',
      'Совет: сделайте короткую паузу перед переносом строки, чтобы текущий текст применился.',
      'Исправлено дублирование текста при перебазировании во время распознавания.',
      'Ручные правки теперь сохраняются при активной диктовке.',
      'Переработано окно настроек: кнопка закрытия (X), улучшен макет.',
    ],
    es: [
      'Soporte para saltos de línea durante la dictado — pulsa Shift+Enter con el micrófono activo.',
      'Consejo: haz una breve pausa antes de insertar un salto de línea.',
      'Corregida la duplicación de texto durante el reconocimiento de voz.',
      'Las ediciones manuales se conservan ahora durante la dictado.',
      'Rediseño del modal de ajustes: botón de cierre (X), diseño más limpio.',
    ],
    uk: [
      'Підтримка перенесення рядка під час диктування — натисніть Shift+Enter, поки мікрофон увімкнено.',
      'Порада: зробіть коротку паузу перед переносом рядка, щоб текст застосувався.',
      'Виправлено дублювання тексту під час активного розпізнавання мови.',
      'Ручні правки тепер зберігаються під час диктування.',
      'Перероблено вікно налаштувань: кнопка закриття (X), покращений макет.',
    ],
    zh: [
      '口述时支持换行 — 麦克风开启时按 Shift+Enter。',
      '提示：插入换行前先短暂暂停，让当前文本生效。',
      '修复了语音识别过程中重新定位时出现的文本重复问题。',
      '口述时手动编辑现在会被保留。',
      '设置窗口重新设计：关闭按钮 (X)，更简洁的布局。',
    ],
    ko: [
      '받아쓰기 중 줄 바꿈 지원 — 마이크가 켜져 있을 때 Shift+Enter를 누르세요.',
      '팁: 줄 바꿈을 삽입하기 전에 현재 텍스트가 적용되도록 잠시 멈추세요.',
      '진행 중인 음성 인식 중 재기본화가 발생할 때 발생하던 텍스트 중복 문제를 수정했습니다.',
      '받아쓰기 중 수동 편집이 이제 보존됩니다.',
      '설정 창 재설계: 닫기 버튼(X), 더 깔끔한 레이아웃.',
    ],
    fr: [
      'Prise en charge des sauts de ligne pendant la dictée — appuyez sur Shift+Entrée pendant que le micro est allumé.',
      'Conseil : faites une courte pause avant d\'insérer un saut de ligne pour que le texte actuel soit appliqué.',
      'Correction de la duplication de texte lors du rebasing pendant la reconnaissance vocale.',
      'Les éditions manuelles sont désormais conservées pendant la dictée.',
      'Redesign du modal des paramètres : bouton de fermeture (X), mise en page plus propre.',
    ],
    pt: [
      'Suporte a quebra de linha durante a ditado — pressione Shift+Enter enquanto o microfone está ligado.',
      'Dica: faça uma breve pausa antes de inserir uma quebra de linha para que o texto atual seja aplicado.',
      'Corrigida a duplicação de texto que ocorria durante o reconhecimento de voz.',
      'As edições manuais agora são preservadas durante o ditado.',
      'Redesign do modal de configurações: botão de fechar (X), layout mais limpo.',
    ],
    hi: [
      'डिक्टेशन के दौरान लाइन ब्रेक सहायता — माइक्रोफ़ोन चालू होने पर Shift+Enter दबाएँ।',
      'टिप: लाइन ब्रेक डालने से पहले थोड़ा रुकें ताकि मौजूदा टेक्स्ट लागू हो सके।',
      'स्पीच रिकग्निशन के दौरान रीबेस होने पर टेक्स्ट डुप्लीकेट की समस्या ठीक की गई।',
      'डिक्टेशन के दौरान मैन्युअल एडिट्स अब सुरक्षित रहेंगे।',
      'सेटिंग्स मोडल का पुनर्डिज़ाइन: बंद करें बटन (X), साफ-सुथरा लेआउट।',
    ],
  },
  '2.2': {
    en: [
      'Improved speech recognition reliability.',
      'Full i18n localization for EN, RU, ES, UK, ZH, KO, FR, PT, HI.',
      'Refined settings modal layout.',
      'Improved Push-to-Talk handling.',
    ],
    ru: [
      'Улучшена надёжность распознавания речи.',
      'Полная мультиязычность: EN, RU, ES, UK, ZH, KO, FR, PT, HI.',
      'Улучшен макет окна настроек.',
      'Улучшена работа режима рации.',
    ],
    es: [
      'Reconocimiento de voz más fiable.',
      'Localización completa: EN, RU, ES, UK, ZH, KO, FR, PT, HI.',
      'Diseño del modal de ajustes refinado.',
      'Mejorada la gestión de Push-to-Talk.',
    ],
    uk: [
      'Покращено надійність розпізнавання мови.',
      'Повна багатомовність: EN, RU, ES, UK, ZH, KO, FR, PT, HI.',
      'Удосконалено макет вікна налаштувань.',
      'Покращено роботу режиму рації.',
    ],
    zh: [
      '语音识别可靠性提高。',
      '完整国际化支持：英语、俄语、西班牙语、乌克兰语、中文、韩语、法语、葡萄牙语、印地语。',
      '设置窗口布局优化。',
      '一键通（对讲机）处理改进。',
    ],
    ko: [
      '음성 인식 안정성 향상.',
      '완전한 i18n 지역화: 영어, 러시아어, 스페인어, 우크라이나어, 중국어, 한국어, 프랑스어, 포르투갈어, 힌디어.',
      '설정 모달 레이아웃 개선.',
      '푸시 투 토크 처리 개선.',
    ],
    fr: [
      'Fiabilité de la reconnaissance vocale améliorée.',
      'Localisation i18n complète : EN, RU, ES, UK, ZH, KO, FR, PT, HI.',
      'Mise en page du modal de paramètres affinée.',
      'Gestion du Push-to-Talk améliorée.',
    ],
    pt: [
      'Confiabilidade do reconhecimento de voz aprimorada.',
      'Localização i18n completa: EN, RU, ES, UK, ZH, KO, FR, PT, HI.',
      'Layout do modal de configurações refinado.',
      'Manuseio do Push-to-Talk aprimorado.',
    ],
    hi: [
      'स्पीच रिकग्निशन की विश्वसनीयता में सुधार।',
      'पूर्ण i18n लोकलाइज़ेशन: EN, RU, ES, UK, ZH, KO, FR, PT, HI।',
      'सेटिंग्स मोडल लेआउट को बेहतर बनाया गया।',
      'पुश-टू-टॉक हैंडलिंग में सुधार।',
    ],
  },
};

export const CURRENT_VERSION = '2.5';

export const VERSIONS = Object.keys(CHANGELOG_DATA).sort().reverse();

export const getChangelog = (version, locale) => {
  const data = CHANGELOG_DATA[version];
  if (!data) return [];
  return data[locale] || data.en || [];
};
