export const languages = [
  {code: 'en-US', name: 'English (US)'},
  {code: 'uk-UA', name: 'Українська'},
  {code: 'ru-RU', name: 'Русский'},
  {code: 'en-GB', name: 'English (UK)'},
  {code: 'af-ZA', name: 'Afrikaans'},
  {code: 'sq-AL', name: 'Shqip (Albanian)'},
  {code: 'am-ET', name: 'አማርኛ (Amharic)'},
  {code: 'ar-SA', name: 'العربية (Arabic)'},
  {code: 'hy-AM', name: 'Հայերեն (Armenian)'},
  {code: 'az-AZ', name: 'Azərbaycan dili'},
  {code: 'eu-ES', name: 'Euskara (Basque)'},
  {code: 'bn-BD', name: 'বাংলা (Bengali)'},
  {code: 'bg-BG', name: 'Български'},
  {code: 'ca-ES', name: 'Català (Catalan)'},
  {code: 'zh-CN', name: '简体中文'},
  {code: 'zh-TW', name: '繁體中文'},
  {code: 'hr-HR', name: 'Hrvatski'},
  {code: 'cs-CZ', name: 'Čeština'},
  {code: 'da-DK', name: 'Dansk'},
  {code: 'nl-NL', name: 'Nederlands'},
  {code: 'et-EE', name: 'Estonian'},
  {code: 'fil-PH', name: 'Filipino'},
  {code: 'fi-FI', name: 'Suomi (Finnish)'},
  {code: 'fr-FR', name: 'Français'},
  {code: 'gl-ES', name: 'Galego'},
  {code: 'ka-GE', name: 'ქართული (Georgian)'},
  {code: 'de-DE', name: 'Deutsch (German)'},
  {code: 'el-GR', name: 'Ελληνικά'},
  {code: 'gu-IN', name: 'ગુજરાતી (Gujarati)'},
  {code: 'he-IL', name: 'עברית (Hebrew)'},
  {code: 'hi-IN', name: 'हिन्दी (Hindi)'},
  {code: 'hu-HU', name: 'Magyar (Hungarian)'},
  {code: 'is-IS', name: 'Íslenska'},
  {code: 'id-ID', name: 'Bahasa Indonesia'},
  {code: 'it-IT', name: 'Italiano'},
  {code: 'ja-JP', name: '日本語 (Japanese)'},
  {code: 'kn-IN', name: 'ಕನ್ನಡ (Kannada)'},
  {code: 'kk-KZ', name: 'Қазақ тілі'},
  {code: 'km-KH', name: 'ខ្មែរ (Khmer)'},
  {code: 'ko-KR', name: '한국어 (Korean)'},
  {code: 'lo-LA', name: 'ລາວ (Lao)'},
  {code: 'lv-LV', name: 'Latviešu'},
  {code: 'lt-LT', name: 'Lietuvių'},
  {code: 'mk-MK', name: 'Македонски'},
  {code: 'ms-MY', name: 'Bahasa Melayu'},
  {code: 'ml-IN', name: 'മലയാളം (Malayalam)'},
  {code: 'mr-IN', name: 'मराठी (Marathi)'},
  {code: 'mn-MN', name: 'Монгол (Mongolian)'},
  {code: 'ne-NP', name: 'नेपाली (Nepali)'},
  {code: 'no-NO', name: 'Norsk (Norwegian)'},
  {code: 'fa-IR', name: 'فارسی (Persian)'},
  {code: 'pl-PL', name: 'Polski'},
  {code: 'pt-BR', name: 'Português (Brazilian)'},
  {code: 'pt-PT', name: 'Português (European)'},
  {code: 'pa-IN', name: 'ਪੰਜਾਬੀ (Punjabi)'},
  {code: 'ro-RO', name: 'Română (Romanian)'},
  {code: 'sr-RS', name: 'Српски (Serbian)'},
  {code: 'si-LK', name: 'සිංහල (Sinhala)'},
  {code: 'sk-SK', name: 'Slovenčina'},
  {code: 'sl-SI', name: 'Slovenščina'},
  {code: 'es-ES', name: 'Español (Spanish)'},
  {code: 'sw-KE', name: 'Kiswahili (Swahili)'},
  {code: 'sv-SE', name: 'Svenska (Swedish)'},
  {code: 'ta-IN', name: 'தமிழ் (Tamil)'},
  {code: 'te-IN', name: 'తెలుగు (Telugu)'},
  {code: 'th-TH', name: 'ไทย (Thai)'},
  {code: 'tr-TR', name: 'Türkçe (Turkish)'},
  {code: 'ur-PK', name: 'اردو (Urdu)'},
  {code: 'uz-UZ', name: 'Oʻzbekcha (Uzbek)'},
  {code: 'vi-VN', name: 'Tiếng Việt (Vietnamese)'},
  {code: 'cy-GB', name: 'Cymraeg (Welsh)'},
  {code: 'xh-ZA', name: 'isiXhosa (Xhosa)'},
  {code: 'zu-ZA', name: 'isiZulu (Zulu)'},
];